### ISSUE TITLE
Minecraft Wiki Links needs to be Updated

### ISSUE THREAD

**Issue by ArkhamCookie** [GoldenDelicios/slabserver-tweaks#2]
The Minecraft wiki has moved to [minecraft.wiki](https://minecraft.wiki) from the Fandom version, [^1]
so the links need to be update to point to the new one.
I **believe** all the links are the same except the domain name.

Example:
```https://minecraft.fandom.com/wiki/Map_item_format#Color_table -> https://minecraft.wiki/wiki/Map_item_format#Color_table```

The just noticed this on the [Reduced enderman griefing](https://github.com/Slabserver/Slabserver-Tweaks/wiki/Reduced-enderman-griefing) page,
but I wouldn't be surprised if there are other links to the old wiki.

[^1]: Related Minecraft Wiki Post: [Minecraft Wiki:Moving from Fandom](https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom)

**Comment by ArkhamCookie** [comment]
I would more than happy to go though and correct all the links.  It would require me to be given write permission for the wiki.

**Comment by DaMarine** [comment]
I am open to us allowing pull requests to the tweaks/docs/wiki repos, but alas that is not trivial for wikis. This hurdle is on my radar for #192 'Tidy Slabserver-Wiki and Slabserver-Documentation' on our staff kanban board though, and I will consider it in trying to find a solution there - I've also widened it's scope to include Slabserver-Tweaks.

For now, this is a good enough way of flagging these to us, so thank you. Cloning the wiki locally and searching doesn't seem to reveal any more fandom links within this repo, so closing.

**Comment by ArkhamCookie** [comment]
I wish they would fix that.  That's why I tend to use a `docs/` folder rather than wikis.
Thanks for fixing it so fast and keep up the good work.
